// Action types
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

// Fetch public ideas
export const FETCH_PUBLIC_IDEAS_SUCCESS = 'FETCH_PUBLIC_IDEAS_SUCCESS';
export const FETCH_PUBLIC_IDEAS_FAILURE = 'FETCH_PUBLIC_IDEAS_FAILURE';

/**
 * fetch user ideas
 */
export const FETCH_USER_IDEAS_SUCCESS = 'FETCH_USER_IDEAS_SUCCESS';
export const FETCH_USER_IDEAS_FAILURE = 'FETCH_USER_IDEAS_FAILURE';

/**
 * fetch single idea
 */
export const FETCH_SINGLE_IDEA_SUCCESS = 'FETCH_SINGLE_IDEA_SUCCESS';
export const FETCH_SINGLE_IDEA_FAILURE = 'FETCH_SINGLE_IDEA_FAILURE';
