// Action types
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

// Fetch public ideas
export const FETCH_PUBLIC_IDEAS_SUCCESS = 'FETCH_PUBLIC_IDEAS_SUCCESS';
export const FETCH_PUBLIC_IDEAS_FAILURE = 'FETCH_PUBLIC_IDEAS_FAILURE';
